server:
  port: 8082
spring:
  profiles:
    active: dev
  application:
    name: ms-movimientoss-bus

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
